#version: '3'
services:
  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://task7p_user:gWvWESNXmPLECSslGIsQbMNCLT3zx5Bw@dpg-cs3krs56l47c73d96220-a.oregon-postgres.render.com/task7p
    restart: "no"
  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "8002:8002"
    environment:
      - PORT=8002
      - DATABASE_URL=postgresql://task7p_user:gWvWESNXmPLECSslGIsQbMNCLT3zx5Bw@dpg-cs3krs56l47c73d96220-a.oregon-postgres.render.com/task7p
    restart: "no"